# Generated by Django 4.2 on 2023-04-13 23:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventCategories",
            fields=[
                (
                    "event_category_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=60)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("default_reminder_time", models.DurationField()),
                ("default_localization", models.CharField(blank=True, max_length=60)),
                ("default_duration_time", models.DurationField()),
                ("default_color", models.CharField(blank=True, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name="PriorityLevels",
            fields=[
                (
                    "priority_level_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=20)),
                ("priority_value", models.IntegerField()),
                ("markdown", models.CharField(blank=True, max_length=1)),
                ("default_reminder_time", models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name="RepeatPatterns",
            fields=[
                (
                    "repeat_pattern_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=60)),
                ("days_interval", models.IntegerField()),
                ("weeks_interval", models.IntegerField()),
                ("months_interval", models.IntegerField()),
                ("years_interval", models.IntegerField()),
                ("number_of_repetitions", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TaskCategories",
            fields=[
                (
                    "task_category_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=60)),
                ("description", models.CharField(max_length=500)),
                ("default_reminder_time", models.DurationField()),
                ("default_localization", models.CharField(max_length=60)),
                ("default_color", models.CharField(max_length=6)),
                ("default_acceptable_slide_time", models.DurationField()),
                (
                    "default_priority_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendar_events.prioritylevels",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("user_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("login", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tasks",
            fields=[
                ("task_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=60)),
                ("description", models.CharField(max_length=500)),
                ("reminder_time", models.DurationField()),
                ("localization", models.CharField(max_length=60)),
                ("creation_date", models.DateTimeField(default=datetime.datetime.now)),
                ("color", models.CharField(max_length=3)),
                ("expected_completion_date", models.DateTimeField()),
                ("deadline", models.DateTimeField()),
                ("acceptable_slide_time", models.DurationField()),
                ("first_occurrence", models.DateTimeField()),
                ("completion_date", models.DateTimeField()),
                ("status", models.IntegerField(choices=[])),
                (
                    "priority_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendar_events.prioritylevels",
                    ),
                ),
                (
                    "repeat_pattern",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendar_events.repeatpatterns",
                    ),
                ),
                (
                    "task_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendar_events.taskcategories",
                    ),
                ),
                (
                    "task_creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendar_events.users",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskOccurrences",
            fields=[
                (
                    "task_occurrence_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("start_time", models.DateTimeField()),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendar_events.tasks",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="taskcategories",
            name="task_category_creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="calendar_events.users"
            ),
        ),
        migrations.AddField(
            model_name="repeatpatterns",
            name="repeat_pattern_creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="calendar_events.users"
            ),
        ),
        migrations.AddField(
            model_name="prioritylevels",
            name="priority_level_creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="calendar_events.users"
            ),
        ),
        migrations.CreateModel(
            name="Notes",
            fields=[
                ("NoteID", models.BigAutoField(primary_key=True, serialize=False)),
                ("Title", models.CharField(max_length=4000)),
                ("Contents", models.CharField(max_length=4000)),
                ("DateOfCreation", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "ModificationDate",
                    models.DateTimeField(default=datetime.datetime.now),
                ),
                (
                    "Creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendar_events.users",
                    ),
                ),
                (
                    "PriorityLevel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendar_events.prioritylevels",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                ("EventID", models.BigAutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=60)),
                ("Description", models.CharField(max_length=500)),
                ("ReminderTime", models.DurationField()),
                ("Localization", models.CharField(max_length=60)),
                ("Duration", models.DurationField()),
                ("CreationDate", models.DateTimeField(default=datetime.datetime.now)),
                ("Color", models.CharField(max_length=3)),
                ("FirstOccurence", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "Creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendar_events.users",
                    ),
                ),
                (
                    "EventCategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendar_events.eventcategories",
                    ),
                ),
                (
                    "PriorityLevel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendar_events.prioritylevels",
                    ),
                ),
                (
                    "RepeatPattern",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendar_events.repeatpatterns",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventOccurrences",
            fields=[
                (
                    "event_occurrence_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("start_time", models.DateTimeField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendar_events.events",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="eventcategories",
            name="default_priority_level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="calendar_events.prioritylevels",
            ),
        ),
        migrations.AddField(
            model_name="eventcategories",
            name="event_category_creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="calendar_events.users"
            ),
        ),
    ]
