# Generated by Django 4.2 on 2023-05-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="status",
            field=models.IntegerField(blank=True, choices=[], null=True),
        ),
    ]
