# Generated by Django 4.2 on 2023-05-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_events", "0002_alter_tasks_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskcategories",
            name="default_deadline",
            field=models.DurationField(null=True),
        ),
    ]
